project:
  type: book

book:
  title: "UW HYAK"
  page-navigation: true
  search: true
  chapters:
    - index.qmd
    - part: docs/start/index.qmd
      chapters:
        - docs/start/introduction.qmd
        - docs/start/connect-ssh.qmd
        - docs/start/hyakvnc.qmd
    - part: docs/compute/index.qmd
      chapters:
        - docs/compute/slurm.qmd
        - docs/compute/apptainer.qmd
        - docs/compute/lmod.qmd
    - part: docs/software/index.qmd
      chapters:
        - docs/software/matlab.qmd
        - docs/software/freesurfer.qmd
        - docs/software/spm_conn.qmd
        - docs/software/afni.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false



