project:
  type: website

website:
  title: "UW Psychology"
  page-navigation: false
  sidebar:
    logo: logo.png
    title: "Computing Resources"
    type: dark
    background: "#523088"
    foreground: "#FFFF"
    style: docked
    contents: auto
format:
  html:
    theme: darkly
    grid:
      sidebar-width: "20%"

